services:
  webapi:
    build:
      context: ../Test.October
      dockerfile: Test.October/Dockerfile
    container_name: StatsWeb
    environment:
      DatabaseSettings:ConnectionString: "Host=db;Database=TradeStatsDB;Username=postgres;Password=postgres"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

